services:
  - type: web
    name: react-naziaportfolio
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    headers:
      - path: /assets/*
        name: Content-Type
        value: text/css